### ISSUE TITLE
Calling ApiVideoMediaRecorder's `stop()` method throws an error if not recording

### ISSUE THREAD

**Issue by hadrianhughes** [apivideo/api.video-typescript-media-recorder#10]
**Describe the bug**
If the `ApiVideoMediaRecorder` is not currently in the recording state and you call `.stop()`, an error is thrown.

**To Reproduce**
1. Instantiate the `ApiVideoMediaRecorder` class
2. Make sure it is not recording
3. Call `.stop()` on the instance

**Expected behavior**
Since the `MediaRecorder` being wrapped by the `ApiVideoMediaRecorder` in the `mediaRecorder` property is set to private, it is impossible to manually check if it is in the recording state or not.

It would make sense either for there to be a getter for the `mediaRecorder` property, or for the `stop()` method to handle the error thrown if not in the recording state.

**Environment (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Brave (Chromium)
 - Version: 1.38.115

**Comment by olivier-lando** [comment]
Hi Hadrian, 

We have added a getMediaRecorderState() method in the last release, and now the resulting promise of `stop()` is rejected when the underlaying call to `mediaRecorder.stop()` fails. 

Hope this helps
