### ISSUE TITLE
Safari fails to upload for recordings longer than 5 seconds

### ISSUE THREAD

**Issue by rc-endeavor** [apivideo/api.video-typescript-media-recorder#3]
Safari 15.3
OSX 12.2.1
Any recording that went longer than 5 seconds in Safari would fail to upload.  Lowering mediaRecorder.start to 2 seconds resolved the issue for me.

this.mediaRecorder.start(2000);

**Comment by ThibaultBee** [comment]
Hello Roy,

Thanks for reporting this issue.
Let us have a look on this. We will get back as soon as we find something.
Is it something that happens with Safari 15.3?

Regards,
Thibault

**Comment by olivier-lando** [comment]
Hi Roy,

We've not been able to reproduce the issue on macOS 12.2.1 / Safari 15.3 (17612.4.9.1.8) . 
The recordings are sent correctly on our side, even if they are several minutes long.

However, to address your issue, we have released a new version with the ability to customize the timeslice value. You can now do:
```javascript
recorder.start({ timeslice: 2000 });
```
Don't hesitate to re-open if it doesn't solve your issue.

Regards
