### ISSUE TITLE
Add public property to option type

### ISSUE THREAD

**Issue by rvddekock** [apivideo/api.video-typescript-media-recorder#5]
When using the typescript media recorder package you can only upload public videos.

The public property needs to be added to the typescript type of this repo and added to the POST request in api.video-typescript-uploader.

**Comment by tpak** [comment]
I'm curious if this would be possible as well. The use case is that we're doing video interviews with job applicants.

**Comment by olivier-lando** [comment]
Hi Rudolph,

As mentioned on https://github.com/apivideo/api.video-typescript-uploader/issues/13, at the moment that's unfortunatly not doable as the API endpoint doesn't support this. If one day the API offers a way to do this we will update the package.

Regards
