### ISSUE TITLE
When a video stops exactly on the end of a slice we get a 400 error uploaded file is empty

### ISSUE THREAD

**Issue by rvddekock** [apivideo/api.video-typescript-media-recorder#8]
**Describe the bug**
When a video stops exactly on the end of a slice we get a 400 error uploaded file is empty error. this only seem to happen on Apple desktop devices not on mobile and only on safari browser. We found the problem when we record and automatically stop the recording at 2 minutes with a timeslice of 3000ms. We have a workaround to change the timeslice to 4100ms so that it wont have an empty packet for the last one. But if a user stops the recording on the end of a slice we might still get the error.
![168670650-d9779c6f-fff1-46d6-9636-d4fde0b656ae2](https://user-images.githubusercontent.com/6572701/169246809-963be58e-4c48-4d63-82ff-57c98f7d5e61.png)

**To Reproduce**
1. Record exactly 2 minutes with timeslice of 3000ms with the continious upload feature
2. And test on safari on a macbook (not on mobile device)

**Expected behavior**
When a video stops on the end of a timeslice it should not give a 400 error.

**Screenshots**

![168670650-d9779c6f-fff1-46d6-9636-d4fde0b656ae2](https://user-images.githubusercontent.com/6572701/169247345-6ef740dc-abc8-4fb2-9584-1400808a20ab.png)

**Environment (please complete the following information):**
 - OS: Apple Mac OS
 - Browser: safari
 - Version: macOS Monterey

**Comment by tpak** [comment]
FYI, the Macbook I was using was running Apple silicon in case it makes a difference. The system clock may behave slightly differently than on the Intel silicon models. 

I keep this MBP up to date at all times.

Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
System Software Overview:
  System Version:	macOS 12.4 (21F79)
  Kernel Version:	Darwin 21.5.0

**Comment by olivier-lando** [comment]
Hi Rudolph & Chris, 
Thanks for these details, we'll fix that issue as soon as possible

**Comment by olivier-lando** [comment]
Hi @rvddekock & @tpak ,

We've released a v1.0.4 that should fix your issue. Can you confirm?

Thanks,

Olivier

**Comment by tpak** [comment]
I will try today and let you know.

**Comment by tpak** [comment]
@olivierapivideo I can confirm this appears to work correctly now. Thanks for the fast turnaround on this and also the player rotation issue yesterday!
